name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            goarch: amd64
          - arch: arm64
            goarch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -o proxy-go-${{ matrix.arch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: proxy-go-${{ matrix.arch }}
          path: proxy-go-${{ matrix.arch }}

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: woodchen
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Prepare binaries
        run: |
          chmod +x proxy-go-*/proxy-go-*
          mv proxy-go-amd64/proxy-go-amd64 proxy-go-amd64/proxy-go
          mv proxy-go-arm64/proxy-go-arm64 proxy-go-arm64/proxy-go

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            woodchen/proxy-go:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/proxy-go:${{ steps.date.outputs.date }}

